heart_disease:
  - I20
  - I21
  - I22
  - I23
  - I24
  - I25
lung_disease:
  - J00
  - J01
  - J02
  - J03
  - J04
  - J05
  - J06
  - J09
  - J10
  - J11
  - J12
  - J13
  - J14
  - J15
  - J16
  - J17
  - J18
  - J40
  - J41
  - J42
  - J43
  - J44
  - J45
  - J46
  - J47
diabetes:
  - E10
  - E11
  - E12
  - E13
  - E14
cancer:
  - C00
  - C01
  - C02
  - C03
  - C04
  - C05
  - C06
  - C07
  - C08
  - C09
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  - C16
  - C17
  - C18
  - C19
  - C20
  - C21
  - C22
  - C23
  - C24
  - C25
  - C26
  - C27
  - C28
  - C29
  - C30
  - C31
  - C32
  - C33
  - C34
  - C35
  - C36
  - C37
  - C38
  - C39
  - C40
  - C41
  - C42
  - C43
  - C44
  - C45
  - C46
  - C47
  - C48
  - C49
  - C50
  - C51
  - C52
  - C53
  - C54
  - C55
  - C56
  - C57
  - C58
  - C59
  - C60
  - C61
  - C62
  - C63
  - C64
  - C65
  - C66
  - C67
  - C68
  - C69
  - C70
  - C71
  - C72
  - C73
  - C74
  - C75
  - C76
  - C77
  - C78
  - C79
  - C80
  - C81
  - C82
  - C83
  - C84
  - C85
  - C86
  - C87
  - C88
  - C89
  - C90
  - C91
  - C92
  - C93
  - C94
  - C95
  - C96
  - C97
hypertension:
  - I10
  - I11
  - I12
  - I13
  - I14
  - I15
stroke:
  - I60
  - I61
  - I62
  - I63
  - I64
kidney_disease:
  - N00
  - N01
  - N02
  - N03
  - N04
  - N05
  - N06
  - N07
  - N17
  - N18
  - N19
liver_disease:
  - K70
  - K71
  - K72
  - K73
  - K74
  - K75
  - K76
  - K77
mental_disorders:
  - F00
  - F01
  - F02
  - F03
  - F04
  - F05
  - F06
  - F07
  - F08
  - F09
  - F10
  - F11
  - F12
  - F13
  - F14
  - F15
  - F16
  - F17
  - F18
  - F19
  - F20
  - F21
  - F22
  - F23
  - F24
  - F25
  - F28
  - F29
  - F30
  - F31
  - F32
  - F33
  - F34
  - F38
  - F39
cognitive_disorders:
  - F00
  - F01
  - F02
  - F03
  - G30
  - G31
inflammatory_diseases:
  - M00
  - M01
  - M02
  - M05
  - M06
  - M08
  - M10
  - M11
  - M12
  - M13
  - L40
  - K50
  - K51
digestive_system_diseases:
  - K20
  - K21
  - K22
  - K23
  - K25
  - K26
  - K27
  - K28
  - K29
  - K30
  - K31
  - K35
  - K36
  - K37
  - K38
  - K40
  - K41
  - K42
  - K43
  - K44
  - K45
  - K46
  - K50
  - K51
  - K52
  - K55
  - K56
  - K57
  - K58
  - K59
  - K60
  - K61
  - K62
  - K63